#ifndef COLLISION_SOLVER_H
#define COLLISION_SOLVER_H
#include "GameObject.h"
#include <utility>

//! CollisionSolver : manages the dispatching of GameObjectCollisions

/*! This class takes the colliding objects generated by the CollisionDetector and
    send them a GameObjectCollision to notify the objects they have been collided.
*/
class CollisionSolver
{
  public:
    void solve(std::pair< GameObject *, GameObject *> collided) ;//!< main function to process the colliding objects

};
#endif// COLLISION_SOLVER_H